default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000
  username: postgres
  password: password

test:
  <<: *default
  database: purrter_test
  
development:
  <<: *default
  database: purrter_development

production:
  <<: *default
  database: purrter_production
