test:
  adapter: postgresql
  database: purrter_test
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: purrter_development
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: purrter_production
  pool: 5
  timeout: 5000
